<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="user" failures="3" tests="4" name="Test" time="37.494" errors="0" timestamp="2020-10-06T02:02:38 EDT">
  <testcase classname="factorialAssignment.testCase1" name="testZero" time="0.809">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;&amp;gt; but was:&amp;lt;The factorial of 0 is: 1&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<> but was:<The factorial of 0 is: 1>
at factorialAssignment.testCase1.testZero(testCase1.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testZero -->
  <testcase classname="factorialAssignment.testCase2" name="testChars" time="0.77"/>
  <testcase classname="factorialAssignment.testCase3" name="testNegative" time="0.918">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;&amp;gt; but was:&amp;lt;Please enter a positive integer&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<> but was:<Please enter a positive integer>
at factorialAssignment.testCase3.testNegative(testCase3.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testNegative -->
  <testcase classname="factorialAssignment.testCase4" name="testBigInt" time="0.602">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;&amp;gt; but was:&amp;lt;The factorial of 171 is: 1.24101807 E+309&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<> but was:<The factorial of 171 is: 1.24101807 E+309>
at factorialAssignment.testCase4.testBigInt(testCase4.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testBigInt -->
</testsuite> <!-- Test -->
